// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {git} from '../models';
import {agentbridge} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<config.ProjectMeta>;

export function CreateSession(arg1:string,arg2:string,arg3:string):Promise<main.SessionDTO>;

export function GetConfig():Promise<config.AppConfig>;

export function GetGitStatus(arg1:string):Promise<git.Status>;

export function GetLayout(arg1:string):Promise<config.SplitNode>;

export function GetScrollback(arg1:string):Promise<Record<string, any>>;

export function InstallAgentCLI(arg1:string):Promise<agentbridge.InstallResult>;

export function KillSession(arg1:string):Promise<void>;

export function ListAgentCLIs():Promise<Array<agentbridge.CLIInfo>>;

export function ListProjects():Promise<Array<config.ProjectMeta>>;

export function ListSessions():Promise<Array<main.SessionDTO>>;

export function OpenInFinder(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PromoteSession(arg1:string,arg2:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<boolean>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveHookIntent(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function SaveActiveScope(arg1:string):Promise<void>;

export function SaveFontSize(arg1:number):Promise<void>;

export function SaveKeybindings(arg1:config.KeybindingOverrides):Promise<void>;

export function SaveLayout(arg1:string,arg2:config.SplitNode):Promise<void>;

export function SaveShell(arg1:string):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function SetFocusedSession(arg1:string):Promise<void>;

export function SetSessionName(arg1:string,arg2:string):Promise<boolean>;

export function UninstallAgentCLI(arg1:string):Promise<void>;

export function WriteSession(arg1:string,arg2:string):Promise<void>;

export function WriteSessionBytes(arg1:string,arg2:string):Promise<void>;
