// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetLayout(arg1) {
  return window['go']['main']['App']['GetLayout'](arg1);
}

export function GetScrollback(arg1) {
  return window['go']['main']['App']['GetScrollback'](arg1);
}

export function InstallAgentCLI(arg1) {
  return window['go']['main']['App']['InstallAgentCLI'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function ListAgentCLIs() {
  return window['go']['main']['App']['ListAgentCLIs']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PromoteSession(arg1, arg2) {
  return window['go']['main']['App']['PromoteSession'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function ResolveHookIntent(arg1, arg2) {
  return window['go']['main']['App']['ResolveHookIntent'](arg1, arg2);
}

export function SaveActiveScope(arg1) {
  return window['go']['main']['App']['SaveActiveScope'](arg1);
}

export function SaveFontSize(arg1) {
  return window['go']['main']['App']['SaveFontSize'](arg1);
}

export function SaveLayout(arg1, arg2) {
  return window['go']['main']['App']['SaveLayout'](arg1, arg2);
}

export function SaveShell(arg1) {
  return window['go']['main']['App']['SaveShell'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SetFocusedSession(arg1) {
  return window['go']['main']['App']['SetFocusedSession'](arg1);
}

export function SetSessionName(arg1, arg2) {
  return window['go']['main']['App']['SetSessionName'](arg1, arg2);
}

export function UninstallAgentCLI(arg1) {
  return window['go']['main']['App']['UninstallAgentCLI'](arg1);
}

export function WriteSession(arg1, arg2) {
  return window['go']['main']['App']['WriteSession'](arg1, arg2);
}

export function WriteSessionBytes(arg1, arg2) {
  return window['go']['main']['App']['WriteSessionBytes'](arg1, arg2);
}
