// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appmode} from '../models';
import {config} from '../models';
import {main} from '../models';
import {core} from '../models';
import {git} from '../models';

export function AboutInfo():Promise<appmode.AboutInfo>;

export function ActiveAgentBinds():Promise<Record<string, string>>;

export function AddProject(arg1:string,arg2:string):Promise<config.ProjectMeta>;

export function CreateSession(arg1:string,arg2:string,arg3:string):Promise<main.SessionDTO>;

export function GetAgentToolsCaps(arg1:string):Promise<core.ToolsCaps>;

export function GetConfig():Promise<config.AppConfig>;

export function GetGitSnapshot(arg1:string):Promise<git.Snapshot>;

export function GetGitStatus(arg1:string):Promise<git.Status>;

export function GetLayout(arg1:string):Promise<config.SplitNode>;

export function GetScrollback(arg1:string):Promise<Record<string, any>>;

export function GitAddWorktree(arg1:string,arg2:string):Promise<git.WorktreeAddResult>;

export function GitCheckout(arg1:string,arg2:string):Promise<git.Result>;

export function GitCommit(arg1:string,arg2:string):Promise<git.Result>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<git.Result>;

export function GitDeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<git.Result>;

export function GitDiscard(arg1:string,arg2:string):Promise<git.Result>;

export function GitDiscardAll(arg1:string):Promise<git.Result>;

export function GitFetch(arg1:string):Promise<git.Result>;

export function GitPruneWorktrees(arg1:string):Promise<git.Result>;

export function GitPull(arg1:string):Promise<git.Result>;

export function GitPush(arg1:string):Promise<git.Result>;

export function GitRemoveWorktree(arg1:string,arg2:string,arg3:boolean):Promise<git.Result>;

export function GitStage(arg1:string,arg2:string):Promise<git.Result>;

export function GitStageAll(arg1:string):Promise<git.Result>;

export function GitStash(arg1:string,arg2:string):Promise<git.Result>;

export function GitStashApply(arg1:string,arg2:string):Promise<git.Result>;

export function GitStashDrop(arg1:string,arg2:string):Promise<git.Result>;

export function GitStashPop(arg1:string,arg2:string):Promise<git.Result>;

export function GitUnstage(arg1:string,arg2:string):Promise<git.Result>;

export function GitUnstageAll(arg1:string):Promise<git.Result>;

export function InstallAgentCLI(arg1:string):Promise<core.InstallResult>;

export function InstallAgentTool(arg1:string,arg2:string,arg3:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function ListAgentCLIs():Promise<Array<core.CLIInfo>>;

export function ListAgentSessions(arg1:string,arg2:string):Promise<Array<core.Session>>;

export function ListAgentTools(arg1:string):Promise<Array<core.ToolItem>>;

export function ListGitBranches(arg1:string):Promise<Array<git.Branch>>;

export function ListGitStashes(arg1:string):Promise<Array<git.StashEntry>>;

export function ListGitWorktrees(arg1:string):Promise<Array<git.Worktree>>;

export function ListProjects():Promise<Array<config.ProjectMeta>>;

export function ListSessions():Promise<Array<main.SessionDTO>>;

export function OpenInFinder(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PromoteSession(arg1:string,arg2:string):Promise<void>;

export function Ready():Promise<boolean>;

export function RemoveProject(arg1:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<boolean>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveHookIntent(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function ResumeAgentSession(arg1:string,arg2:string,arg3:string):Promise<main.SessionDTO>;

export function SaveActiveScope(arg1:string):Promise<void>;

export function SaveFontSize(arg1:number):Promise<void>;

export function SaveKeybindings(arg1:config.KeybindingOverrides):Promise<void>;

export function SaveLayout(arg1:string,arg2:config.SplitNode):Promise<void>;

export function SaveShell(arg1:string):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function SaveUIPrefs(arg1:config.UIPrefs):Promise<void>;

export function SearchScrollback(arg1:string,arg2:Array<string>):Promise<Array<Record<string, any>>>;

export function SetAgentToolEnabled(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetFocusedSession(arg1:string):Promise<void>;

export function SetSessionName(arg1:string,arg2:string):Promise<boolean>;

export function SetSessionPinned(arg1:string,arg2:boolean):Promise<boolean>;

export function UninstallAgentCLI(arg1:string):Promise<void>;

export function UninstallAgentTool(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateAgentTool(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteSession(arg1:string,arg2:string):Promise<void>;

export function WriteSessionBytes(arg1:string,arg2:string):Promise<void>;
